### ISSUE TITLE
put counter into address bar

### ISSUE THREAD

**Issue by Riajyuu** [Loirooriol/tab-counter-plus#14]
If you don't know how, here it is: 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/pageAction

**Comment by Loirooriol** [comment]
Why? Page actions are supposed to be specific to the page you are viewing (that's why they are in the address bar). That's not the case for a tab counter.

> Page actions are for actions that are only relevant to particular pages (such as "bookmark the current tab"). If they are relevant to the browser as a whole (such as "show all bookmarks"), use a browser action instead.

**Comment by Loirooriol** [comment]
Closing as wontfix since you didn't provide any convincing reason.

**Comment by ohhai** [comment]
Reason might be just to see counter on Android always -- like the default one which supports max number of 99.

**Comment by Loirooriol** [comment]
But in Firefox for Android there is already a native tab counter. Are you maybe using Focus or something else?

**Comment by ohhai** [comment]
Yes, there is native, that's what I meant under "default". It's just a problems of people with tabs number > 99 :) Native counter shows infinity sign beyond that.
