### ISSUE TITLE
Hide count tab if less than xx opened tabs

### ISSUE THREAD

**Issue by jeje07bis** [Loirooriol/tab-counter-plus#22]
Hi!

Is it possible to hide the button if there is less than xx opened tabs?

Thank you :)

**Comment by Loirooriol** [comment]
Doesn't seem possible. Unlike pageAction, there is no API to hide a browserAction. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction
