### ISSUE TITLE
[Feature Request] add "number of windows"

### ISSUE THREAD

**Issue by RAPXT** [Loirooriol/tab-counter-plus#24]
Please add "number of windows" too, if possible. Thank you.

**Comment by Loirooriol** [comment]
Do you want the toolbar icon to show the number of windows instead of tabs? Or in the panel when clicking the icon?

**Comment by RAPXT** [comment]
It would be good if it could show number of tabs and windows on mouseover aswell when the user clicks on the icon.

I have attached an screenshot of another addon as an example:
![example](https://user-images.githubusercontent.com/53192319/62662683-271c7780-b975-11e9-9dc3-d8a2c719ecb1.png)

BTW: Is it possible to have the extension icon not in the same row as the urlbar, but instead in the same row as the tabbar?

I´m sorry for my poor english, but i just wanted to suggest some ideas. Well i hope you can understand what i´m trying to describe ;-)

**Comment by Loirooriol** [comment]
Done!

I haven't added it into the icon tooltip, since the code that takes care of updating the icon may not track the number of windows in certain configurations.

I could change that, or perform a request like I do in the popup, but for now it didn't seem worth it.
