### ISSUE TITLE
Advices

### ISSUE THREAD

**Issue by davidp88** [Loirooriol/tab-counter-plus#31]
1.Think completely and work and that thinking should be done at once,as little thinking causes mistakes.

2.If u add a new feature or update an existing feature think of all the ways of how it can be improved

3.Increase patience

4.Avoid laziness in work

5.Do important work first

6.If u can't repro a bug normally then test it thoroughly and try to repro for 2 to 3 times.

**Comment by Loirooriol** [comment]
OK
