### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by Bananaman** [Loirooriol/tab-counter-plus#46]
You've done an awesome job creating an efficient and well-written extension. All other tab counters slowed my Firefox to a crawl. Yours has no performance impact whatsoever. I love that it shows tabs per window, total tabs and open windows, which lets me get an overview **and motivation** as I work on getting these tabs down one by one and close these windows one by one. :laughing: Thank you so much!

**Comment by Gitoffthelawn** [comment]
I agree completely! Great job! 👍🏾

**Comment by dandv** [comment]
This extension has been the best answer to my [Superuser.com question about displaying the tab count in Firefox](https://superuser.com/questions/1591015/display-tab-count-in-firefox-without-permission-to-snoop-on-tabs/1591018)!

**Comment by Loirooriol** [comment]
Glad it works for you all! I typically have a few thousand tabs open so good performance is top priority.

**Comment by Gitoffthelawn** [comment]
@Loirooriol Any tips for successfully using such a large quantity of open tabs in Firefox?  I personally find that after about 50-75 open tabs, memory consumption gets quite high and things get laggy.  Of course, I generally don't use browser disk caching, so perhaps that's the key difference.

**Comment by Loirooriol** [comment]
Well, most of my tabs are lazy: when Firefox starts using too much RAM or CPU, I restart it or kill the content processes in about:processes. But 50-75 loaded tabs shouldn't be a problem, unless they are all playing videos or doing intensive things.
