### ISSUE TITLE
API

### ISSUE THREAD

**Issue by nicksae** [Loirooriol/tab-counter-plus#9]
Hello, my name is Niccolò, i'm a student. I wanted to ask you if is possible to get the url API of the tab counter to gain access from another application to it. I was able to get some data from a weather website making this kind of request

{
    "http_method" : "get",
    "url" : "https://api.openweathermap.org/data/2.5/weather?q=Rome&APPID=c4711e9c77f3a039dc073d9312c4db52",
    "response_dict" : "body",
    "parse_type" : "json"
}

It would be possible to use the same framework to get the number of tabs in the application only changing the url? It's for a project at uni for which i'm struggling and would appreciate your help very much, thank you Niccolò

**Comment by Loirooriol** [comment]
@nicksae Hello, Niccolò. I'm not much convinced that this would be an useful feature for Tab Counter Plus, but I would like to get some more details about what you are trying to do.

What kind of "another application" would need this? Another WebExtension, a desktop program?

And how would you connect to my add-on to get this data? The files in a webextension can be accessed via the moz-extension:// protocol, but you need to know the UUID of the extension, which right now I think it's created at install time but there are plans to change it at each restart of the browser.

Also, I think WebExtensions provide no way to create some kind of server-side JS script which produces the output of the request.

**Comment by nicksae** [comment]
Hi, first of all thanks for replying. The application I'm using is a desktop application called Max/Msp, in few words I want to get data from the web that show user's behaviour, and particularly data that are representative of possible distractions (I am basing the theory on a book called "The shallow" by Nicholas Carr, this is a small article that explain it  https://www.theguardian.com/books/2010/sep/11/shallows-internet-changing-way-think) and turn them into sounds into the application. Ideally this would work real time with the navigation, making it audible and I wanted to start with the number of tabs open. 

Now, I don't know much about coding and I am not sure how Max/Msp can communicate with extensions. The way it communicated with the openweather API was pretty straightforward using the framework I posted above. Do you think will be much different doing the same with your extension?

If is not possible, how do i know where the file is stored on my computer? (You said using moz-extension:// protocol) Can you tell me more about how it works roughly or link some documentation please? 

Last point,  the server side JS script could be something like this https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Working_with_the_Tabs_API ?

For my project even to be able to explain why it didn't work would helpful, so thank you again and sorry if most of the stuff don't make sense but I have just started learning all this and is not easy.

**Comment by Loirooriol** [comment]
@nicksae OK, now I understand better what you are trying to achieve. I think the proper way to do it is [Native messaging](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging).

However, I don't want Tab Counter Plus to require the permission to communicate with other programs. I could consider it as an [optional permission](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/optional_permissions), but not possible for `nativeMessaging` (and even if possible, most probably I wouldn't do it).

So what you can do is fork my add-on and find out some way to send messages to Max/Msp using that API. I wish you good luck, but I'm closing this since it would be too out of scope.
